version: '3.9'

networks:
  application_spring:
    driver: bridge

services:
  spring_app_1:
    container_name: spring_app_1
    build: .
    networks:
      - application_spring
    depends_on:
      - postgres_sql
    links:
      - postgres_sql
    env_file:
      - env/.env

  spring_app_2:
    container_name: spring_app_2
    build: .
    networks:
      - application_spring
    depends_on:
      - postgres_sql
    links:
      - postgres_sql
    env_file:
      - env/.env

  postgres_sql:
    container_name: postgres_sql
    image: postgres
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
    networks: 
      - application_spring
    ports:
      - "2222:5432"
    restart: always
    env_file:
      - env/.env
      
  redis:
    hostname: redis-container
    container_name: redis-container-db
    image: redis:7.2.3
    ports:
      - "6379:6379"
    networks:
      - application_spring

  nginx:
    image: docker.io/nginx:1.25.3
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring_app_1
      - spring_app_2
    networks:
      - application_spring
    ports:
      - 8080:80