name: CI-CD

on:
  push:
    branches: ["dev"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Autenticação do DockerHub
    - uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    
    - name: Construção da imagem Docker
    - uses: docker/build-push-action@v5.0.0 # Construção da imagem docker
      with:
        context: . # Aonde está a imagem docker
        file: ./dockerfile
        push: true
        tags:
          andretipolt/project_order_spring_image:v1
