name: CI-CD

on:
  push:
    branches: ["dev", "main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup Java JDK
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Tests
      # run: docker run -d -p 6379:6379 redis:7.2.3 ; ./Back-End-Spring/mvnw test -Ptest
      run: docker run -d -p 6379:6379 redis:7.2.3 ; chmod +x mvnw ; ./Back-End-Spring/mvnw test -Ptest

  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticação do DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v5.0.0 # Construção da imagem docker
        with:
          context: "./Back-End-Spring/" # Aonde está a imagem docker
          file: dockerfile
          push: true
          tags:
            andretipolt/project_order_spring_image:1.0.${{github.run_number}}
